# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
      validator.unique.date.exam:
          class: My\FormRPBundle\Validator\Constraint\DateMajorityValidator
          tags:
              - { name: validator.constraint_validator, alias: date_majority }
